name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6
      options: --network-alias main
      env:
        RAILS_ENV: test
        POSTGRES_HOST: postgres
        CAPYBARA_HOST: main

    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      chrome:
        image: selenium/standalone-chrome-debug:3.141.59

    steps:
      - uses: actions/checkout@v2

      - name: bundle config
        run: |
          bundle config path vendor/bundle
      - uses: actions/cache@v1
        id: bundle_cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: bundle install
        run: |
          bundle install -j4 -r3 --path vendor/bundle

      - name: Install nodejs and yarn
        run: |
          apt update -y && apt install -y nodejs npm
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          apt update -y && apt install -y yarn
      - name: Get yarn cache dir
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn_cache
        with:
          path: ${{ steps.yarn_cache_dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Test
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails db:create db:schema:load
          bundle exec rails yarn:install webpacker:compile
          bundle exec rspec

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: screenshots
          path: tmp/screenshots
